name: Ping test

description: Simple test that validates that an action can update a workflow status.

inputs:
  token:
    description: 'The GitHub token to use for authentication'
    required: true

runs:
  using: composite
  steps:
    - name: Get token
      id: get_workflow_token
      uses: peter-murray/workflow-application-token-action@v2
      with:
        application_id: ${{ inputs.APPLICATION_ID }}
        application_private_key: ${{ inputs.APPLICATION_PRIVATE_KEY }}

    # Update GitHub status for dispatch events
    - name: "Update GitHub Status for this ref"
      if: github.event_name == 'repository_dispatch'
      uses: "docker://cloudposse/github-status-updater"
      with:
        args: "-action update_state -state success -ref ${{ github.event.client_payload.pull_request.head.sha }} -repo ${{ github.event.client_payload.github.payload.repository.name }}"
      env:
        GITHUB_TOKEN: ${{ inputs.token }}
        GITHUB_CONTEXT: "ping"
        GITHUB_DESCRIPTION: "pong"
        GITHUB_TARGET_URL: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
        GITHUB_REF: ${{ github.event.client_payload.pull_request.head.ref }}
        GITHUB_OWNER: ${{ github.event.client_payload.github.payload.repository.owner.login }}
