name: Auto approve and merge

description: Auto approve and merge

inputs:
  # either pass in a token, or an app id and private key
  token:
    description: 'The GitHub token to use for authentication'
    required: false
  application_id:
    description: 'The GitHub App ID'
    required: false
  application_private_key:
    description: 'The GitHub App private key'
    required: false
  branch:
    description: 'The branch to merge into'
    required: false
    default: 'main'
  checks:
    description: 'The checks to wait for before merging'
    required: false
    default: |-
      checks:
        - context: 'e2e-tests'
        - context: 'pre-commit-checks'

runs:
  using: composite
  steps:
    - name: Get token
      id: get_installation_token
      uses: peter-murray/workflow-application-token-action@v2
      if: ${{ !inputs.token }}
      with:
        application_id: ${{ inputs.application_id }}
        application_private_key: ${{ inputs.application_private_key }}

    - name: Auto approve
      uses: hmarr/auto-approve-action@v3
      with:
        github-token: ${{ inputs.token || steps.get_installation_token.outputs.token }}
        review-message: "Auto approved"

    - name: Workaround for GitHub Action not being able to do CODEOWNER approval or be a member of a team
      uses: defenseunicorns/delivery-github-actions-workflows/.github/actions/repo-config@main
      with:
        application_id: ${{ inputs.application_id }}
        application_private_key: ${{ inputs.application_private_key }}
        token: ${{ inputs.token }}
        branch: ${{ inputs.branch }}
        checks: ${{ inputs.checks }}
        require_code_owner_reviews: false

    - name: Auto Merge
      shell: bash -e -o pipefail {0}
      env:
        GH_TOKEN: ${{ inputs.TOKEN || steps.get_installation_token.outputs.token }}
      run: |
        gh pr merge ${{ github.head_ref }} --auto -s

    - name: Workaround for GitHub Action not being able to do CODEOWNER approval or be a member of a team
      uses: defenseunicorns/delivery-github-actions-workflows/.github/actions/repo-config@main
      with:
        application_id: ${{ inputs.application_id }}
        application_private_key: ${{ inputs.application_private_key }}
        token: ${{ inputs.token }}
        branch: ${{ inputs.branch }}
        checks: ${{ inputs.checks }}
        require_code_owner_reviews: true
