# Attribution for a bunch of this goes to CloudPosse
# https://github.com/cloudposse/actions/blob/master/.github/workflows/test-command.yml

name: e2e-test

on:
  workflow_call: 
    secrets:
      token:
        description: "GitHub API token, used to checkout caller repo code"
        required: true

jobs:

  # Parse the command, so we can decide which tests to run. Examples: "/test all", "/test validate", "/test e2e"
  # We can do as many of these as we want to get as granular as we want.
  parse:
    runs-on: ubuntu-latest
    outputs:
      run-ping: ${{ steps.parse.outputs.run-ping }}
      run-e2e-commercial-insecure: ${{ steps.parse.outputs.run-e2e-commercial-insecure }}
      run-e2e-govcloud-secure: ${{ steps.parse.outputs.run-e2e-govcloud-secure }}
    steps:
      # - name: Checkout Repo
      #   uses: actions/checkout@v3
      #   with:
      #     token: ${{ secrets.token }}
      #     repository: ${{ github.repository }}
      #     ref: "refs/heads/main"
      - name: ls everything
        shell: bash -e -o pipefail {0}
        run: ls -lahRt .
      - name: Parse Args
        id: parse
        uses: zack-is-cool/delivery-github-actions-workflows/.github/actions/parse-test@main

  # Update the comment that triggered the /test command to show the run url
  comment:
    runs-on: ubuntu-latest
    steps:
      # - name: Checkout Repo
      #   uses: actions/checkout@v3
      #   with:
      #     token: ${{ secrets.token }}
      #     repository: ${{ github.repository }}
      #     ref: ${{ github.ref_name }}
      - name: Update Comment
        uses: zack-is-cool/delivery-github-actions-workflows/.github/actions/comment@main
        with:
          token: ${{ secrets.token }}

  # Do a simple ping/pong status update to validate things are working
  ping:
    runs-on: ubuntu-latest
    needs: parse
    if: needs.parse.outputs.run-ping == 'true'
    steps:
      # - name: Checkout Repo
      #   uses: actions/checkout@v3
      #   with:
      #     token: ${{ secrets.token }}
      #     repository: ${{ github.repository }}
      #     ref: ${{ github.ref_name }}
      - name: Ping Test
        uses: zack-is-cool/delivery-github-actions-workflows/.github/actions/ping@main
        with:
          token: ${{ secrets.token }}

  # Run the E2E insecure tests on the commercial account
  e2e-commercial-insecure:
    runs-on: ubuntu-latest
    needs: parse
    if: needs.parse.outputs.run-e2e-commercial-insecure == 'true'
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.token }}
          repository: ${{ github.repository }}
          ref: ${{ github.ref_name }}
      - name: Run E2E Tests
        uses: zack-is-cool/delivery-github-actions-workflows/.github/actions/e2e@main
        with:
          token: ${{ secrets.token }}
          role-to-assume: ${{ secrets.AWS_COMMERCIAL_ROLE_TO_ASSUME }}
          region: us-east-2
          github-context: "test / e2e-commercial-insecure"
          test-to-run: "insecure"

  # Run the E2E secure tests on the govcloud account
  e2e-govcloud-secure:
    runs-on: ubuntu-latest
    needs: parse
    if: needs.parse.outputs.run-e2e-govcloud-secure == 'true'
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.token }}
          repository: ${{ github.repository }}
          ref: ${{ github.ref_name }}
      - name: Run E2E Tests
        uses: zack-is-cool/delivery-github-actions-workflows/.github/actions/e2e@main
        with:
          token: ${{ secrets.token }}
          role-to-assume: ${{ secrets.AWS_GOVCLOUD_ROLE_TO_ASSUME }}
          region: us-gov-east-1
          github-context: "test / e2e-govcloud-secure"
          test-to-run: "secure"
