# This autoformats using pre-commit, then triggers an automatic test run if and only if Renovate is the author and the PR was just opened. See ADR #0008.
name: renovate-test
on:
  pull_request:
    # WARNING: DO NOT ADD MORE EVENT TYPES HERE! Because this workflow will push a new commit to the PR in the Autoformat step, adding more event types may cause an infinite loop.
    types:
      - opened

permissions:
  id-token: write
  contents: write

defaults:
  run:
    # We need -e -o pipefail for consistency with GitHub Actions' default behavior
    shell: bash -e -o pipefail {0}

jobs:
  renovate-test:
    if: github.event.client_payload.github.actor == 'renovate[bot]' || github.actor == 'renovate[bot]'
    runs-on: ubuntu-latest
    steps:
      - name: Get buildharness software versions
        id: buildharness-software-versions
        uses: defenseunicorns/delivery-github-actions-workflows/.github/actions/get-buildharness-software-versions@main
        with:
          application_id: ${{ secrets.APPLICATION_ID }}
          application_private_key: ${{ secrets.APPLICATION_PRIVATE_KEY }}
          token: ${{ secrets.TOKEN }}

      - name: Autoformat
        uses: defenseunicorns/delivery-github-actions-workflows/.github/actions/autoformat@main
        with:
          application_id: ${{ secrets.APPLICATION_ID }}
          application_private_key: ${{ secrets.APPLICATION_PRIVATE_KEY }}
          token: ${{ secrets.TOKEN }}
          github-context: "update / autoformat"
          buildharness_version: ${{ steps.buildharness-software-versions.outputs.buildharness_version }}
          golang_version: ${{ steps.buildharness-software-versions.outputs.golang_version }}
          terraform_version: ${{ steps.buildharness-software-versions.outputs.terraform_version }}
          zarf_version: ${{ steps.buildharness-software-versions.outputs.zarf_version }}
