# This autoformats using pre-commit, then triggers an automatic test run if and only if Renovate is the author and the PR was just opened. See ADR #0008.
name: renovate-test
on:
  pull_request:
    # WARNING: DO NOT ADD MORE EVENT TYPES HERE! Because this workflow will push a new commit to the PR in the Autoformat step, adding more event types may cause an infinite loop.
    types:
      - opened

permissions:
  id-token: write
  contents: write

defaults:
  run:
    # We need -e -o pipefail for consistency with GitHub Actions' default behavior
    shell: bash -e -o pipefail {0}

jobs:
  renovate-test:
    if: github.event.client_payload.github.actor == 'renovate[bot]' || github.actor == 'renovate[bot]'
    runs-on: ubuntu-latest
    steps:
      - name: Get token
        id: get_installation_token
        uses: peter-murray/workflow-application-token-action@v2
        if: ${{ !env.TOKEN }}
        with:
          application_id: ${{ secrets.NARWHAL_BOT_APP_ID }}
          application_private_key: ${{ secrets.NARWHAL_BOT_SECRET }}
        env:
          TOKEN: ${{ secrets.TOKEN }}

      - name: Autoformat
        uses: defenseunicorns/delivery-github-actions-workflows/.github/actions/autoformat@main
        with:
          token: ${{ secrets.token || steps.get_installation_token.outputs.token }}
          github-context: "update / autoformat"
