name: pre-commit

on:
  workflow_call:
    secrets:
      APPLICATION_ID:
        description: "GitHub App ID"
        required: true
      APPLICATION_PRIVATE_KEY:
        description: "GitHub App private key"
        required: true

    inputs:
      check-types:
        description: "List of check types to run"
        type: string
        required: false
        default: '["common", "terraform", "golang", "renovate"]' #json matrix

jobs:
  pre-commit-checks:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        check-type: ${{ fromJSON(inputs.check-types) }}
    steps:

      - name: Get token
        id: get_workflow_token
        uses: peter-murray/workflow-application-token-action@v2
        with:
          application_id: ${{ secrets.APPLICATION_ID }}
          application_private_key: ${{ secrets.APPLICATION_PRIVATE_KEY }}

      - name: pre-commit
        uses: defenseunicorns/delivery-github-actions-workflows/.github/actions/pre-commit@main
        with:
          check-type: ${{ matrix.check-type }}
          token: ${{ steps.get_workflow_token.outputs.token }}
