name: pre-commit

  ### Usage 
  # ```yaml
  #   name: Terraform ChatOps
  #   on:
  #     workflow_call:
    
  #   permissions:
  #     pull-requests: write
  #     id-token: write
  #     contents: read
  
  #   jobs:
  #     pre-commit:
  #       uses: zack-is-cool/delivery-github-actions-workflows/.github/workflows/pre-commit.yml@main
  #       secrets:
  #         token: $\{\{ secrets.PAT \}\}
  # ```

on:
  workflow_call:
    secrets:
      token:
        description: "GitHub API token, used to checkout caller repo code"
        required: false
    inputs:
      check-types:
        description: "List of check types to run"
        type: string
        required: false
        # default: '["common", "terraform", "golang", "renovate"]'
        default: common terraform golang renovate

jobs:

  debug:
    runs-on: ubuntu-latest
    steps:
    - uses: hmarr/debug-action@v2
    - name: Dump github.event.client_payload context
      env:
        PAYLOAD_CONTEXT: ${{ toJson(github.event.client_payload) }}
      run: echo "$PAYLOAD_CONTEXT" | jq .

  common:
    runs-on: ubuntu-latest
    steps:
      - name: pre-commit
        uses: zack-is-cool/delivery-github-actions-workflows/.github/actions/pre-commit@main
        with:
          check-type: common
          token: ${{ secrets.token }}

  pre-commit-checks:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        check-type: ${{ toJson(inputs.check-types) }}
    steps:
      - name: pre-commit
        uses: zack-is-cool/delivery-github-actions-workflows/.github/actions/pre-commit@main
        with:
          check-type: ${{ matrix.check-type }}
          token: ${{ secrets.token }}
