name: pre-commit

  ### Usage
  # ```yaml
  # name: pre-commit

  # on:
  #   pull_request:

  # permissions:
  #   pull-requests: write
  #   id-token: write
  #   contents: read

  # jobs:
  #   pre-commit:
  #     uses: defenseunicorns/delivery-github-actions-workflows/.github/workflows/pre-commit.yml@main
  #     secrets:
  #       token: ${{ secrets.PAT}}
  #     with:
  #       check-types: '["common", "terraform", "golang"]'
  # ```

on:
  workflow_call:
    # secrets:
    #   token:
    #     description: "GitHub API token, used to checkout caller repo code"
    #     required: false
    secrets:
      APPLICATION_ID:
        description: "GitHub App ID"
        required: true
      APPLICATION_PRIVATE_KEY:
        description: "GitHub App private key"
        required: true

    inputs:
      check-types:
        description: "List of check types to run"
        type: string
        required: false
        default: '["common", "terraform", "golang", "renovate"]' #json matrix

jobs:
  pre-commit-checks:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        check-type: ${{ fromJSON(inputs.check-types) }}
    steps:
      - name: pre-commit
        uses: defenseunicorns/delivery-github-actions-workflows/.github/actions/pre-commit@ci/app_token_wip
        with:
          check-type: ${{ matrix.check-type }}
          APPLICATION_ID: ${{ secrets.APPLICATION_ID }}
          APPLICATION_PRIVATE_KEY: ${{ secrets.APPLICATION_PRIVATE_KEY }}
