name: |-
  pre-commit

  ### Usage 
  ```yaml
    name: Terraform ChatOps
    on:
      workflow_call:
    
    permissions:
      pull-requests: write
      id-token: write
      contents: read
  
    jobs:
      pre-commit:
        uses: zack-is-cool/delivery-github-actions-workflows/.github/workflows/pre-commit.yml@main
        secrets:
          token: $\{\{ secrets.PAT \}\}
  ```

on:
  workflow_call:
    secrets:
      token:
        description: "GitHub API token"
        required: true

jobs:

  debug:
    runs-on: ubuntu-latest
    steps:
    - uses: hmarr/debug-action@v2
    - name: Dump github.event.client_payload context
      env:
        PAYLOAD_CONTEXT: ${{ toJson(github.event.client_payload) }}
      run: echo "$PAYLOAD_CONTEXT" | jq .

#testing full path to an action, probably won't work
  common:
    runs-on: ubuntu-latest
    steps:
      # - name: Checkout repo
      #   uses: actions/checkout@v3
      #   with:
      #     repository: "zack-is-cool/delivery-github-actions-workflows"
      #     ref: "refs/heads/main"

      - name: pre-commit
        uses: zack-is-cool/delivery-github-actions-workflows/.github/actions/pre-commit@main
        with:
          check-type: common
          # token: ${{ secrets.token }}

# testing not checking out the repo inside
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.token }}
          repository: "zack-is-cool/delivery-github-actions-workflows"
          ref: "refs/heads/main"

      - name: pre-commit
        uses: zack-is-cool/delivery-github-actions-workflows/.github/actions/pre-commit@main
        with:
          check-type: terraform
          # token: ${{ secrets.token }}

  golang:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.token }}
          repository: "zack-is-cool/delivery-github-actions-workflows"
          ref: "refs/heads/main"

      - name: pre-commit
        uses: ./.github/actions/pre-commit
        with:
          check-type: golang
          token: ${{ secrets.token }}

  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.token }}
          repository: "zack-is-cool/delivery-github-actions-workflows"
          ref: "refs/heads/main"

      - name: pre-commit
        uses: ./.github/actions/pre-commit
        with:
          check-type: renovate
          token: ${{ secrets.token }}
