name: |-
  pre-commit

  ### Usage 
  ```yaml
    name: Terraform ChatOps
    on:
      workflow_call:
    
    permissions:
      pull-requests: write
      id-token: write
      contents: read
  
    jobs:
      pre-commit:
        uses: defenseunicorns/delivery-github-actions-workflows/.github/workflows/pre-commit-pr.yml@main
        secrets:
          token: $\{\{ secrets.PAT \}\}
  ```

on:
  workflow_call:
    secrets:
      token:
        description: "GitHub API token"
        required: true

jobs:

  common:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: pre-commit
        uses: ./.github/actions/pre-commit
        with:
          check-type: common
          token: ${{ secrets.PAT }}

  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: pre-commit
        uses: ./.github/actions/pre-commit
        with:
          check-type: terraform
          token: ${{ secrets.PAT }}

  golang:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: pre-commit
        uses: ./.github/actions/pre-commit
        with:
          check-type: golang
          token: ${{ secrets.PAT }}

  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: pre-commit
        uses: ./.github/actions/pre-commit
        with:
          check-type: renovate
          token: ${{ secrets.PAT }}
