# On every push to main, run release-please to automatically handle the release process.
name: release-please

on:
  workflow_call:
    secrets:
      TOKEN:
        description: "GitHub App Token"
        required: false
      APPLICATION_ID:
        description: "The GitHub App ID"
        required: false
      APPLICATION_PRIVATE_KEY:
        description: "The GitHub App Private Key"
        required: false

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Get token
        id: get_installation_token
        uses: peter-murray/workflow-application-token-action@8e4e6fbf6fcc8a272781d97597969d21b3812974 # v4
        if: ${{ !env.TOKEN }}
        with:
          application_id: ${{ secrets.APPLICATION_ID }}
          application_private_key: ${{ secrets.APPLICATION_PRIVATE_KEY }}
          organization: ${{ github.repository_owner }}
        env:
          TOKEN: ${{ secrets.TOKEN }}

      - uses: googleapis/release-please-action@7987652d64b4581673a76e33ad5e98e3dd56832f # v4
        with:
          token: ${{ secrets.token || steps.get_installation_token.outputs.token }}
          command: manifest
