# On every push to main, run release-please to automatically handle the release process.
name: release-please

on:
  workflow_call:
    secrets:
      TOKEN:
        description: "GitHub App Token"
        required: false
      APPLICATION_ID:
        description: "The GitHub App ID"
        required: false
      APPLICATION_PRIVATE_KEY:
        description: "The GitHub App Private Key"
        required: false

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Get token
        id: get_installation_token
        uses: peter-murray/workflow-application-token-action@dc0413987a085fa17d19df9e47d4677cf81ffef3 # v3
        if: ${{ !env.TOKEN }}
        with:
          application_id: ${{ secrets.APPLICATION_ID }}
          application_private_key: ${{ secrets.APPLICATION_PRIVATE_KEY }}
          organization: ${{ github.repository_owner }}
        env:
          TOKEN: ${{ secrets.TOKEN }}

      - uses: googleapis/release-please-action@3f4784dbc19347947972489b7ed79193ff704b10 # v4
        with:
          token: ${{ secrets.token || steps.get_installation_token.outputs.token }}
          command: manifest
