name: repo-config

# configure repository settings and branch protection rules if caller ref is main

on:
  workflow_call:
    secrets:
      TOKEN:
        description: "GitHub App Token"
        required: false
      APPLICATION_ID:
        description: "The GitHub App ID"
        required: false
      APPLICATION_PRIVATE_KEY:
        description: "The GitHub App Private Key"
        required: false
    inputs:
      branch:
        type: string
        description: "Branch to configure"
        required: false
        default: "main"
      checks: #allows status checks to be configurable
        type: string
        description: "YAML formatted required status checks"
        required: false
        default: |-
          checks:
            - context: 'e2e-tests'
            - context: 'pre-commit-checks'

jobs:
  repo-config:
    runs-on: ubuntu-latest
    # check if caller sha is main
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Repo Config
        uses: defenseunicorns/delivery-github-actions-workflows/.github/actions/repo-config@main
        with:
          application_id: ${{ secrets.APPLICATION_ID }}
          application_private_key: ${{ secrets.APPLICATION_PRIVATE_KEY }}
          token: ${{ secrets.TOKEN }}
          branch: ${{ inputs.branch }}
          checks: ${{ inputs.checks }}
          require_code_owner_reviews: true
