name: update

on:
  workflow_call:
    secrets:
      APPLICATION_ID:
        description: The GitHub App ID
        required: true
      APPLICATION_PRIVATE_KEY:
        description: The GitHub App Private Key
        required: true
jobs:

  # Parse the command
  parse:
    runs-on: ubuntu-latest
    outputs:
      run-ping: ${{ steps.parse.outputs.run-ping }}
      run-autoformat: ${{ steps.parse.outputs.run-autoformat }}
    steps:
      - name: Parse Args
        id: parse
        uses: defenseunicorns/delivery-github-actions-workflows/.github/actions/parse-update@main

  # Update the comment that triggered the /test command to show the run url
  comment:
    runs-on: ubuntu-latest
    steps:

      - name: Get token
        id: get_workflow_token
        uses: peter-murray/workflow-application-token-action@v2
        with:
          application_id: ${{ secrets.APPLICATION_ID }}
          application_private_key: ${{ secrets.APPLICATION_PRIVATE_KEY }}

      - name: Update Comment
        uses: defenseunicorns/delivery-github-actions-workflows/.github/actions/comment@main
        with:
          token: ${{ steps.get_workflow_token.outputs.token }}

  # Do a simple ping/pong status update to validate things are working
  ping:
    runs-on: ubuntu-latest
    needs: parse
    if: needs.parse.outputs.run-ping == 'true'
    steps:

      - name: Get token
        id: get_workflow_token
        uses: peter-murray/workflow-application-token-action@v2
        with:
          application_id: ${{ secrets.APPLICATION_ID }}
          application_private_key: ${{ secrets.APPLICATION_PRIVATE_KEY }}

      - name: Ping Test
        uses: defenseunicorns/delivery-github-actions-workflows/.github/actions/ping@main
        with:
          token: ${{ steps.get_workflow_token.outputs.token }}

  # Update generated content
  autoformat:
    runs-on: ubuntu-latest
    needs: parse
    if: needs.parse.outputs.run-autoformat == 'true'
    steps:

      - name: Get token
        id: get_workflow_token
        uses: peter-murray/workflow-application-token-action@v2
        with:
          application_id: ${{ secrets.APPLICATION_ID }}
          application_private_key: ${{ secrets.APPLICATION_PRIVATE_KEY }}

      - name: Autoformat
        uses: defenseunicorns/delivery-github-actions-workflows/.github/actions/autoformat@main
        with:
          token: ${{ steps.get_workflow_token.outputs.token }}
          github-context: "update / autoformat"
