name: update

on:
  workflow_call:
    secrets:
      TOKEN:
        description: "GitHub App Token"
        required: false
      APPLICATION_ID:
        description: "The GitHub App ID"
        required: false
      APPLICATION_PRIVATE_KEY:
        description: "The GitHub App Private Key"
        required: false
      GPG_PRIVATE_KEY:
        description: "The GPG private key to use for signing commits"
        required: true
      GPG_KEY_PASSPHRASE:
        description: "The passphrase for the GPG private key"
        required: true

jobs:
  # Parse the command
  parse:
    runs-on: ubuntu-latest
    outputs:
      run-ping: ${{ steps.parse.outputs.run-ping }}
      run-autoformat: ${{ steps.parse.outputs.run-autoformat }}
    steps:
      - name: Parse Args
        id: parse
        uses: defenseunicorns/delivery-github-actions-workflows/.github/actions/parse-update@main

  # Update the comment that triggered the /test command to show the run url
  comment:
    runs-on: ubuntu-latest
    steps:
      - name: Update Comment
        uses: defenseunicorns/delivery-github-actions-workflows/.github/actions/comment@main
        with:
          application_id: ${{ secrets.APPLICATION_ID }}
          application_private_key: ${{ secrets.APPLICATION_PRIVATE_KEY }}
          token: ${{ secrets.TOKEN }}

  # Do a simple ping/pong status update to validate things are working
  ping:
    runs-on: ubuntu-latest
    needs: parse
    if: needs.parse.outputs.run-ping == 'true'
    steps:
      - name: Ping Test
        uses: defenseunicorns/delivery-github-actions-workflows/.github/actions/ping@main
        with:
          application_id: ${{ secrets.APPLICATION_ID }}
          application_private_key: ${{ secrets.APPLICATION_PRIVATE_KEY }}
          token: ${{ secrets.TOKEN }}

  # Update generated content
  autoformat:
    runs-on: ubuntu-latest
    needs: parse
    if: needs.parse.outputs.run-autoformat == 'true'
    steps:
      - name: Autoformat
        uses: defenseunicorns/delivery-github-actions-workflows/.github/actions/autoformat@main
        with:
          application_id: ${{ secrets.APPLICATION_ID }}
          application_private_key: ${{ secrets.APPLICATION_PRIVATE_KEY }}
          token: ${{ secrets.TOKEN }}
          github-context: "update / autoformat"
